name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Archive
        run: |
          mkdir -p cloudflare-warp-hosts-manager-${{ github.ref_name }}
          cp warp-tunnel-hosts.bat hosts.txt cloudflare-warp-hosts-manager-${{ github.ref_name }}/
          zip -r cloudflare-warp-hosts-manager-${{ github.ref_name }}.zip cloudflare-warp-hosts-manager-${{ github.ref_name }}/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          files: cloudflare-warp-hosts-manager-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
